/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#cbd9f2",
        "surface-container-highest": "#e3e1ec",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-dim": "#dad9e3",
        "surface-variant": "#e3e1ec",
        "surface-tint": "#565e74",
        "secondary-fixed-dim": "#c3c0ff",
        secondary: "#4a41e1",
        "on-primary-fixed-variant": "#3e465b",
        "on-surface": "#1a1b22",
        "on-error": "#ffffff",
        surface: "#fbf8ff",
        "on-secondary-fixed-variant": "#3323cc",
        "tertiary-fixed-dim": "#b9c7e0",
        "inverse-surface": "#2f3038",
        "tertiary-fixed": "#d5e3fc",
        "tertiary-dim": "#465469",
        "secondary-fixed": "#e2dfff",
        "on-primary": "#ffffff",
        "primary-container": "#565e74",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e7f1",
        "on-secondary-container": "#fffbff",
        primary: "#3e465b",
        "inverse-on-surface": "#f1effa",
        "tertiary-container": "#515f74",
        "primary-fixed": "#dae2fc",
        "on-secondary-fixed": "#0f0069",
        "on-surface-variant": "#45464c",
        "surface-container-low": "#f4f2fd",
        "error-dim": "#4e0309",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "secondary-container": "#645efa",
        "secondary-dim": "#4135d8",
        "surface-container-lowest": "#ffffff",
        "primary-dim": "#4a5268",
        outline: "#76777d",
        "on-background": "#1a1b22",
        "on-tertiary-fixed": "#0d1c2e",
        "surface-bright": "#fbf8ff",
        error: "#ba1a1a",
        "surface-container": "#eeedf7",
        "on-primary-fixed": "#131b2e",
        "on-primary-container": "#d0d8f2",
        background: "#fbf8ff",
        tertiary: "#39475b",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        display: "Inter",
        mono: ["Roboto Mono", "monospace"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
