/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      colors: {
        // Stitch Design System - Exact tokens from Stitch HTML
        background: '#f6fafe',
        'on-background': '#171c1f',
        primary: {
          DEFAULT: '#1d2b3e',
          container: '#334155',
          fixed: '#d5e3fd',
          'fixed-dim': '#b9c7e0',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#9eadc5',
        'on-primary-fixed': '#0d1c2f',
        'on-primary-fixed-variant': '#3a485c',
        secondary: {
          DEFAULT: '#505f76',
          container: '#d0e1fb',
          fixed: '#d3e4fe',
          'fixed-dim': '#b7c8e1',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#54647a',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        tertiary: {
          DEFAULT: '#222a3e',
          container: '#384055',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#a4acc5',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        surface: {
          DEFAULT: '#f6fafe',
          bright: '#f6fafe',
          dim: '#d6dade',
          tint: '#515f74',
          variant: '#dfe3e7',
          container: {
            DEFAULT: '#eaeef2',
            high: '#e4e9ed',
            highest: '#dfe3e7',
            low: '#f0f4f8',
            lowest: '#ffffff',
          },
        },
        'on-surface': {
          DEFAULT: '#171c1f',
          variant: '#44474c',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: {
          DEFAULT: '#75777d',
          variant: '#c5c6cd',
        },
        'inverse-surface': '#2c3134',
        'inverse-on-surface': '#edf1f5',
        'inverse-primary': '#b9c7e0',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.04em' }],
        'display-md': ['2.75rem', { lineHeight: '1.1', letterSpacing: '-0.04em' }],
        'headline-md': ['1.75rem', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-sm': ['1.5rem', { lineHeight: '1.25', fontWeight: '600' }],
        'title-lg': ['1.375rem', { lineHeight: '1.4' }],
        'title-md': ['1.125rem', { lineHeight: '1.4' }],
        'title-sm': ['1rem', { lineHeight: '1.4' }],
        'body-lg': ['1rem', { lineHeight: '1.6' }],
        'body-md': ['0.875rem', { lineHeight: '1.6' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5' }],
        'label-lg': ['0.875rem', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        'label-md': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.05em' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.05em' }],
      },
      boxShadow: {
        'ambient': '0 20px 40px -10px rgba(42, 52, 57, 0.06)',
        'glass': '0 8px 32px rgba(42, 52, 57, 0.08)',
      },
    },
  },
  plugins: [],
}
